micronaut:
  application:
    name: api
  server:
    port: 8082
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            IdentityServer:
              url: 'https://localhost:5001/.well-known/openid-configuration/jwks'
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /microstream/**
        httpMethod: GET
        access:
          - isAnonymous()
---
consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 0.1
---
#microstream:
#  rest:
#    enabled: true
#  storage:
#    order:
#      root-class: 'fete.bird.entities.Root'
#      storage-directory: '/Users/san/project/Fetebird-Microservice/src/order/infrastructure/src/main/resources'
#      storage-directory: '/Users/san/project/Sample'